### PR TITLE
fix: search addonBefore error and popover out boundaries

### LINKED ISSUE #931: Search Input getting error in the console ,not recognize the `addonBefore &  x-out-ofboundaries
### Description

**1. when opening the search popover** 
1540 Warning: React does not recognize the `addonBefore` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `addonbefore` instead. If you accidentally passed it from a parent component, remove it from the DOM element....
Screen Shot 2020-03-25 at 7 36 47

**2. when scrolling out of the screen with an open popover.**
Warning: Received `true` for a non-boolean attribute `x-out-of-boundaries`.
If you want to write it to the DOM, pass a string instead: x-out-of-boundaries="true" or x-out-of-boundaries={value.toString()}...
image001
 
Thanks 
Ben Oron 
Front End Developer, 
SAP Fieldglass,

### Versions
**fundamental-react:**
0.8
---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### PR DESCRIPTION
**Pull request by smohtadi**
### Description
Fixes :
- Search error when popover is triggered. Cause by li element being created in SearchInput and passed to MenuList were it gets addonBefore prop appended. Used Menu.Item instead.
- Popover error when open and window scrolls down.

fixes #931

### CODE REVIEW

File: src/utils/_Popper.js [hunk 1]
```diff
@@ -122,7 +122,7 @@ class Popper extends React.Component {
                             ref={ref}
                             style={{ ...style, ...popperProps.style }}
                             // eslint-disable-next-line no-undefined
-                            x-out-of-boundaries={!!outOfBoundaries || undefined}
+                            x-out-of-boundaries={!!outOfBoundaries ? 'true' : undefined}
```
Comment (jbadan) [inline src/utils/_Popper.js]: Would this work if we just had  `x-out-of-boundaries={!!outOfBoundaries}`?

**Comment by jbadan** [comment]
@smohtadi thank you for your contribution! Can you sign the CLA agreement linked by the comment? If you have signed it and it's not working, check that the email address you use for git commits is the same as the email address associated with your account.

File: src/utils/_Popper.js (hunk 1 above)
Comment (smohtadi) [reply src/utils/_Popper.js]: I tried it, and it throws an error: "If you used to conditionally omit it with x-out-of-boundaries={condition && value}, pass x-out-of-boundaries={condition ? value : undefined} instead." It seems  x-out-of-boundaries expects either a string when true or an undefined when false.
