### PR TITLE
fix: use momentjs for calendar and datepicker

### LINKED ISSUE #493: Calendar Component: back button for month does not work when certain days selected
### Description

Calendar component does not work when clicking the back button if the current date selected does not exist in the previous month.

Repro steps: 
1. set date to March 29, 30 or 31; This will also work for May 31, July 31, October 31 and December 31st
1. click back button

### Versions
**fundamental-react:** 0.5.0
**fiori-fundamentals:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### LINKED ISSUE #550: Calendar component behaving erratically
### Description

See https://github.com/SAP/fundamental-ngx/issues/855
https://github.com/SAP/fundamental-vue/issues/324

Due to the 5/31 showing in the "June" month of the calendar, all the click behavior for the next month is skipping June.

### Versions
**fundamental-react:** 0.5.3
**fiori-fundamentals:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### LINKED ISSUE #703: Bug. Calendar Breaks when pass a null date value
### Description
The calendar appears to give JavaScript error if a null value is passed to it. 
This seems to be an similar issue to one in the ngx calendar in this ticket: https://github.com/SAP/fundamental-ngx/issues/831 although in that case, there was not error, but it was deemed invalid.

A null value should be accepted by the calendar with no errors, and not deemed as an invalid date.

### Versions
**fundamental-react:**
**fundamental-styles:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### PR DESCRIPTION
**Pull request by jacobdevera**
### Description
Refactors `Calendar` and `DatePicker` to use momentjs. Attempting to get rid of redundant logic covered by moment.

fixes #703
fixes #550
fixes #493

### CODE REVIEW

File: src/Calendar/Calendar.js [hunk 1]
```diff
@@ -11,51 +12,41 @@ class Calendar extends Component {
...
+    // sync the selected date of the calendar with the date picker
     static getDerivedStateFromProps(updatedPropsParent, previousStates) {
+        const { customDate, enableRangeSelection } = updatedPropsParent;
 
-        if (typeof updatedPropsParent.customDate === 'undefined') {
+        if (typeof customDate === 'undefined') {
             return null;
         }
 
-        //If range is enabled and the date from the parent component does not match the array dates of the states then states are updated
```
Comment (jacobdevera) [inline src/Calendar/Calendar.js]: This was one of the hardest parts to deal with. Ideally, this would not be deriving state from props, but mainly wanted to focus on simplifying logic rather than try to overhaul the whole component at once. Hopefully it is at least a bit more readable.

File: src/DatePicker/DatePicker.test.js [hunk 2]
```diff
@@ -142,77 +141,53 @@ describe('<DatePicker />', () => {
...
 
         wrapper.find('input[type="text"]')
             .simulate('change', { target: { value: `${startDate}-${endDate}` } });
 
         wrapper.find('input[type="text"]').simulate('keypress', { key: 'Enter' });
 
-        expect(wrapper.state('arrSelectedDates')).toEqual('undefined');
-    });
-
-    test('entering invalid range dates', () => {
```
Comment (jacobdevera) [inline src/DatePicker/DatePicker.test.js]: DatePicker used to arbitrarily set a limit of 3000 for the year. I do not think we need to impose this limitation now that moment is handling validation.

File: src/DatePicker/DatePicker.js [hunk 3]
```diff
@@ -221,54 +112,18 @@ class DatePicker extends Component {
...
-                let formatDate =
-                    firstDateMonth + '/' + firstDateDay + '/' + firstDateYear;
-
-                this.setState({
-                    arrSelectedDates: date,
-                    formattedDate: formatDate
-                });
+            let formatDate = date[0].format('MM/DD/YYYY');
+            if (!!date[1]) {
+                formatDate += '-' + date[1].format('MM/DD/YYYY');
```
Comment (meganaconley) [inline src/DatePicker/DatePicker.js]: Instead of hardcoding month/day/year could we use `L` and set the locale so it's always localized?

**Comment by jacobdevera** [comment]
Bundle size has increased over the 150 kb which causes builds to fail.
` Package size limit has exceeded by 52.39 KB
  Size limit:   150 KB
  Package size: 202.39 KB with all dependencies, minified and gzipped
  Loading time: 4.1 s     on slow 3G
  Running time: 272 ms    on Snapdragon 410
  Total time:   4.4 s`

Wonder if we should disable some locales, or revert back to consumers manually providing the month/day names.

**Comment by jbadan** [comment]
Can you see if there's an easy fix as well to cleanup the code examples on the docs site?

Screen Shot 2019-12-09 at 1 47 10 PM
Screen Shot 2019-12-09 at 1 47 15 PM

File: src/Calendar/Calendar.js [hunk 4]
```diff
@@ -69,40 +59,54 @@ class Calendar extends Component {
...
+        const {
+            disableWeekends,
+            disableAfterDate,
+            disableBeforeDate,
+            blockedDates,
+            disableWeekday,
+            disablePastDates,
+            disableFutureDates,
+            disabledDates
+        } = this.props;
```
Comment (jacobdevera) [inline src/Calendar/Calendar.js]: These props now accept `Date` objects again instead of moment objects so consumers don't need to worry about importing moment. The Dates are just wrapped in moment inside. This fixes the entire moment objects' props being listed out on the docs site, but the API might actually be better handled this way in the first place.
