### PR TITLE
fix: initialize visual regression testing

### LINKED ISSUE #491: Infrastructure/testing feature: integrate puppeteer or other similar testing library
### Description
We should think about implementing [puppeteer](https://github.com/GoogleChrome/puppeteer) to create some automated interaction testing. 

@jeffredodd has successfully implemented this in the @concur/nui-widgets component library.

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### PR DESCRIPTION
**Pull request by jbadan**
### Description
This pr initializes visual regression testing to make upgrading versions of fundamental-styles less painful/labor intensive.

This automatically takes a screenshot of every storybook story. See https://storybook.js.org/docs/testing/automated-visual-testing/ for more technical information.

We extend this setup to add puppeteer integration testing in the future. 

This is placed in a separate folder so that it does not slow down development by running each time you run `npm run test:dev`.

Also integrated into CI

Also removed a couple unneeded files/scripts/packages.

fixes #491

### CODE REVIEW

File: config/jest/cssTransform.js [hunk 1]
```diff
@@ -1,16 +0,0 @@
-/* eslint-disable strict */
```
Comment (jbadan) [inline config/jest/cssTransform.js]: not being used anywhere

File: config/jest/fileTransform.js [hunk 2]
```diff
@@ -1,32 +0,0 @@
-/* eslint-disable strict */
```
Comment (jbadan) [inline config/jest/fileTransform.js]: not being used anywhere

File: config/jest/jest.config.js [hunk 3]
```diff
@@ -1,10 +1,9 @@
-
 module.exports = {
-    'rootDir': '../../',
+    'rootDir': '../../src/',
```
Comment (jbadan) [inline config/jest/jest.config.js]: limit to `src` directory so that visual regression tests are not run on every commit/every test run

File: package.json [hunk 4]
```diff
@@ -37,14 +37,17 @@
     "start:playground": "npm run storybook",
     "std-version": "standard-version -m \"chore(release): version %s build ${TRAVIS_BUILD_NUMBER} [ci skip]\"",
     "storybook": "start-storybook -p 12123",
+    "storybook:ci": "start-storybook -p 12123 --ci --quiet",
```
Comment (jbadan) [inline package.json]: The `--ci` flag stops this from launching storybook.

File: visual-regression-testing/storyshots.test.js [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+
+const beforeScreenshot = (page) => {
+    return page
+        .emulate(view)
+        .then(resp => resp)
+        .catch(ex => console.error(ex));
+};
+
+initStoryshots({
+    test: imageSnapshot({
```
Comment (markpalfreeman) [inline visual-regression-testing/storyshots.test.js]: So I imagine this is the code that actually runs all the visual comparisons?

It will always just run over every single story, right?

File: package.json [hunk 6]
```diff
@@ -37,14 +37,17 @@
...
     "test:coveralls": "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || echo -e \"Coveralls failed.\"",
     "test:dev": "jest --config=./config/jest/jest.config.js",
-    "test:watch": "npm run test:dev -- --watch",
-    "test": "npm run test:watch",
-    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive"
+    "test": "npm run test:dev -- --watch",
+    "test:visual:dev": "BABEL_ENV=test jest --config=./visual-regression-testing/jest.config.js",
+    "test:visual:update:dev": "npm run test:visual:dev -- --updateSnapshot",
+    "test:visual": "server-test storybook:ci http-get://localhost:12123 test:visual:dev",
+    "test:visual:update": "server-test storybook:ci http-get://localhost:12123 test:visual:update:dev"
```
[the remark this answers is not in the document]
Comment (jbadan) [reply package.json]: So it's just reusing the ci script so that storybook doesn't launch. It's meant to be manual and isn't in the travis config.

File: visual-regression-testing/storyshots.test.js (hunk 5 above)
Comment (jbadan) [reply visual-regression-testing/storyshots.test.js]: yes

File: config/jest/setup.js [hunk 7]
```diff
@@ -1,5 +1,6 @@
 import Adapter from 'enzyme-adapter-react-16';
 import { configure } from 'enzyme';
+import registerRequireContextHook from 'babel-plugin-require-context-hook/register';
```
[the remark this answers is not in the document]
Comment (jbadan) [reply config/jest/setup.js]: Try removing it and see what happens 😆 It's needed for line 7 in `storyshots.test.js`

**Comment by jbadan** [comment]
@bcullman yes, this is just the setup. You'll run `npm run test:visual:update` when you need to update the tests.

File: package.json (hunk 6 above)
[the remark this answers is not in the document]
Comment (markpalfreeman) [reply package.json]: Sorry, when should `test:visual:update:dev` be run then?

[the remark this answers is not in the document]
Comment (jbadan) [reply package.json]: `test:visual:update:dev` is run inside `test:visual:update` - storybook needs to be running for it to be able to take screenshots

[the remark this answers is not in the document]
Comment (jbadan) [reply package.json]: this is a 2 minute read that will clarify why: https://storybook.js.org/docs/testing/automated-visual-testing/

[the remark this answers is not in the document]
Comment (markpalfreeman) [reply package.json]: I did read that; to me, it's getting confusing which scripts to use in a regular workflow and which are for convenience of CI or another script.

Since it's not called anywhere else, what are your thoughts on nixing `test:visual:update:dev` entirely and writing it inline? Or is there value in keeping both?
```
"test:visual:update": "server-test storybook:ci http-get://localhost:12123 test:visual:dev -- --updateSnapshot"
```

_If I'm the only one, feel free to ignore._

[the remark this answers is not in the document]
Comment (jbadan) [reply package.json]: It would be great, but that's not how `server-test` works. You can't pass the argument like that in here - it doesn't work. Feel free to try, maybe I did it wrong 🤷‍♀

[the remark this answers is not in the document]
Comment (markpalfreeman) [reply package.json]: I see, so it's a CLI limitation. It looks like it allows shorthand aliases for npm scripts, but you can also use the whole command surrounded by quotes. 

```
"test:visual:update": "server-test storybook:ci http-get://localhost:12123 'npm run test:visual:dev -- --updateSnapshot'"
```

I'll leave it up to you if you think it's valuable enough to change; I just know too many npm scripts can actually make things **more** confusing when reading over them later.

[the remark this answers is not in the document]
Comment (jbadan) [reply package.json]: Cool! I didn't know you could do it that way. Feel free to push a change if you want it, I don't care either way.

File: .eslintignore [hunk 8]
```diff
@@ -6,4 +6,5 @@
 *.svg
 *.sh
 *.md
-node_modules/**
\ No newline at end of file
+node_modules/**
+*.png
```
Comment (greg-a-smith) [inline .eslintignore]: This seems potentially overbearing.  What about `visual-regression-testing/**/*.png`?

File: package.json (hunk 4 above)
Comment (greg-a-smith) [reply package.json]: To avoid having too many duplicate commands, I believe we could rewrite this as:
```
"storybook:ci": "npm run storybook -- --ci --quiet"
```

File: .eslintignore (hunk 8 above)
Comment (jbadan) [reply .eslintignore]: to be fair, we never want eslint to run on a png - this isn't the gitignore

Comment (markpalfreeman) [reply .eslintignore]: I'm actually confused why any of the file extensions are needed if we only are linting `.js, .jsx`?

Comment (jbadan) [reply .eslintignore]: the whitelist doesn't seem to be working 🤷‍♀ try taking this out

Comment (markpalfreeman) [reply .eslintignore]: > Note: `--ext` is only used when the arguments are directories. If you use glob patterns or file names, then `--ext` is ignored.

I bet if we changed to `eslint src --ext .js,.jsx` this would work :/

Comment (jbadan) [reply .eslintignore]: Did you try it?

Comment (markpalfreeman) [reply .eslintignore]: Yeah, but I'm having trouble pushing to this branch atm... I can follow-up afterward with a quick PR.

Comment (greg-a-smith) [reply .eslintignore]: @jbadan Good point. I didn't realize this was the eslint ignore file.  Carry on...
