### PR TITLE
fix: fundamental Switch state doesn't refresh 

### LINKED ISSUE #977: fundamental Switch state doesn't refresh
### Description
// With code below, when clicking the test button, Switch's checked state should be refreshed but in fact it's not.

import { Switch } from "fundamental-react";

const SwitchTest = () => {
  const [value, setValue] = useState(true);
  const handleClick = () => {
    setValue(!value);
  }
  return `<div><div><Button onClick={handleClick}>test</Button></div > <SwitchWraper checked={value} /></div>`;
};

const SwitchWraper = (props: any) => {
  return `<Switch {...props}></Switch>`;
}

export const FundamentalSwitchIssue = () => {
  return `<SwitchTest />`;
}

### Versions
**fundamental-react:**
0.9.0
---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### PR DESCRIPTION
**Pull request by rjstyles**
### Description
Deriving Switch's checked state from the `checked` prop, which fixes the refresh of checked state on update of the component.

fixes #977

### CODE REVIEW

File: src/Switch/Switch.js [hunk 1]
```diff
@@ -31,6 +31,10 @@ const Switch = React.forwardRef(({
 
     let [isChecked, setIsChecked] = useState(!!checked);
 
+    useEffect(() => {
+        if (checked) setIsChecked(checked);
+    }, [checked]);
+
```
Comment (jbadan) [inline src/Switch/Switch.js:37]: @rjstyles Can you add a test for this? Thanks!

Comment (skvale) [reply src/Switch/Switch.js:37]: I think we'd want to remove the `if(checked)` so it could set the state to checked=false
```jsx
    useEffect(() => {
        setIsChecked(checked);
    }, [checked]);
```

Comment (rjstyles) [reply src/Switch/Switch.js:37]: > @rjstyles Can you add a test for this? Thanks!

Sure, will do that

Comment (rjstyles) [reply src/Switch/Switch.js:37]: Yeah @skvale, Thanks for the review, we can do something like below to also handle  if `checked` is `null` or `undefined`

```
useEffect(() => {
    setIsChecked(!!checked);
}, [checked]);
```

@jbadan I will add the tests for this.

**Comment by dariadomagala** [comment]
Hello team! 
Is there a chance that you will do a 0.13.2 patch release with this bug fix? We need just this one fix and switching to 0.14rc breaks too many things
