### PR TITLE
fix: Only export components when publishing

### LINKED ISSUE #105: Consider separating the library code from the examples (Playground)
Currently the library is mixed with the example page. The index.tsx for example both exports the components and bootstraps the demo application.

The storybook project ([https://github.com/storybooks/storybook](https://github.com/storybooks/storybook)) does pretty much the same than what the Playground is designed for in my opinion.
Using Storybook, the documentation is written in so called stories. They are stored aside the components they describe and are then picked up by the storybook scripts. Additionally stoybook provides a UI that showcases the components and provides functionality such as event logging, knobs (changing props), responsive preview, generating the interface documentation from typescript code and much more.
Example:
[React official storybook](https://storybooks-official.netlify.com/?selectedKind=Components%7CForm%2FButton&selectedStory=with%20knobs&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook-addon-viewport%2Faddon-panel)

When the library is published the stories can be easily filtered using a .npmignore file. 

If you consider this a valid option I would be happy to provide an example for this project.

<details>
<summary>Example for a story:</summary>

```typescript

import *  as React from 'react';
import { storiesOf } from '@storybook/react';

import { wInfo } from '../utils';
import { Tabs } from './tabs';
import { Tab } from './tab';
import { action } from '@storybook/addon-actions';
import { text } from '@storybook/addon-knobs';
import { Story } from '../story';

const info = `
### Notes 
This control is used to navigate between frequently accessed, distinct content categories.
They allow for navigation between two or more content views.
When the header is clicked, the section's content is displayed.

### Do
* Use on content-heavy pages that would otherwise require a significant 
  amount of scrolling to access the various sections.
* Be concise on the navigation labels, ideally one or two words rather than a phrase.

### Usage
* Don’t use the Pivot to link to a new page.
* Don’t use the Pivot to link to hidden content.
~~~js
<Tabs />
~~~`;

(storiesOf('Components/Tabs', module) as any).addWithJSX(
    'Tabs',
    wInfo(info)(() => {
        return (
            <Story>
                <div>
                    <Tabs
                        onSelectTab={action('on-select-tab')}
                        selectedTab={
                            text('selectedTab', null) !== null && text('selectedTab', null) !== ''
                                ? text('selectedTab', null)
                                : undefined
                        }
                    >
                        <Tab key={'tab-1'} title={{id: 'dummy', defaultMessage: 'Tab 1'}}>
                            Content for Tab 1
                        </Tab>
                        <Tab key={'tab-2'} title={{id: 'dummy', defaultMessage: 'Tab 2'}}>
                            Content for Tab 2
                        </Tab>
                        <Tab key={'tab-2'} title={{id: 'dummy', defaultMessage: 'Disabled Tab'}} disabled={true}>
                            Content for Tab 2
                        </Tab>

                    </Tabs>

                    <h3>Tabs with icons</h3>
                    <Tabs
                        onSelectTab={action('on-select-tab')}
                        selectedTab={
                            text('selectedTab', null) !== null && text('selectedTab', null) !== ''
                                ? text('selectedTab', null)
                                : undefined
                        }
                    >
                        <Tab key={'tab-1'} title={{id: 'dummy', defaultMessage: 'Tab 1'}} icon={'sap-icon://edit'}>
                            Content for Tab 1
                        </Tab>
                        <Tab key={'tab-2'} title={{id: 'dummy', defaultMessage: 'Tab 2'}} icon={'sap-icon://list'}>
                            Content for Tab 2
                        </Tab>

                        <Tab
                            key={'tab-2'}
                            title={{id: 'dummy', defaultMessage: 'Tab 2'}}
                            icon={'sap-icon://error'}
                            iconColor={'Critical'}
                        >
                            Content for Tab 2
                        </Tab>

                        <Tab
                            key={'tab-2'}
                            title={{id: 'dummy', defaultMessage: 'Tab 2'}}
                            icon={'sap-icon://accept'}
                            iconColor={'Positive'}
                        >
                            Content for Tab 2
                        </Tab>
                    </Tabs>
                </div>
            </Story>
        );
    })
);

```
</details>

### PR DESCRIPTION
**Pull request by jeffredodd**
Hey everyone, the goal of this PR is to only publish our components to `npm` and to leave the tests, component documentation, and other CreateReactApp leftovers behind. This will reduce the payload we send to consumers and simply our outputted package while leaving the structure mostly intact to allow for simple contributions and also resolves #105. 

I have performed the following...

- Migrated required docs (application) files to `_playground`
- Updated Babel to ignore tests, component documentation, and new `_playground` folder
- Updated main `index.js` file to no longer have documentation site components
- Altered `Routes.js` to point to existing components correctly

Feel free to pull this down and test the changes i've made and let me know what you think. It might help to poke around on `master`'s `dist` folder first to see what was omitted in this branch. 

This branch also should not go in until publishing on `master` is fixed.

### CODE REVIEW

**Comment by jeffredodd** [comment]
Also I'm up for a name thats different from `_playground`. I just figured `_` indicates private so that was a good start for us.

File: src/index.js [hunk 1]
```diff
@@ -1,197 +1,67 @@
...
-    TileGrid,
-    ProductTileContent,
-    Toggle,
-    Tree,
-    Shellbar
-};
-
-ReactDOM.render(<App />, document.getElementById('root'));
-registerServiceWorker();
+export { ActionBar } from '../src/ActionBar/ActionBar';
```
Comment (greg-a-smith) [inline src/index.js]: I think all of these should be rewritten to _NOT_ include the `src` directory as I am still seeing the `src` directory in the path in the `dist` directory.

So:
```
export { ActionBar } from '../src/ActionBar/ActionBar';
```
should become:
```
export { ActionBar } from './ActionBar/ActionBar';
```

**Comment by greg-a-smith** [comment]
I spoke with @jeffredodd, who is out sick, about taking over this PR to get it merged.
