### PR TITLE
fix: update currentYear on date selection

### LINKED ISSUE #357: Calendar Component: currentYear should be updated on date selection for consistentcy
### Description

Related to: https://github.com/SAP/fundamental-react/issues/334

The same problem is present with the currentYear state. 

### Versions
**fundamental-react:** current
**fiori-fundamentals:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### PR DESCRIPTION
**Pull request by chrismanciero**
### Description
Set the currentYear value to the selected date object. 

fixes #357

### CODE REVIEW

File: src/Calendar/Calendar.js [hunk 1]
```diff
@@ -139,6 +139,7 @@ export class Calendar extends Component {
         if (!this.props.enableRangeSelection) {
             this.setState({
                 currentDateDisplayed: date,
+                currentYear: date,
                 selectedDate: date,
```
Comment (greg-a-smith) [inline src/Calendar/Calendar.js]: Is it strange that we have 3 different state variables (`currentDateDisplayed`, `currentYear`, `selectedDate`) that are all being set to the same value?  Seems like they should either be set to different values or the code that depends on them should just reference a single stored value.

Comment (jbadan) [reply src/Calendar/Calendar.js]: @greg-a-smith I agree, but I think it might be better to save that work for an overall refactoring effort instead of putting more time into this. Thoughts?

Comment (greg-a-smith) [reply src/Calendar/Calendar.js]: @jbadan Agreed.  That's probably a much larger effort.

Comment (chrismanciero) [reply src/Calendar/Calendar.js]: I agree we should refactor this control. as a side not i did remove the currentYear property and updated the code and tests to work off the currentDateDisplayed property instead 😄
