### PR TITLE
fix: Close SearchInput popover after selecting an item.

### LINKED ISSUE #938: search input not closed after select item
### Description

search input not closed after select item 
### Versions
**fundamental-react:**
0.8
---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### PR DESCRIPTION
**Pull request by BenOron**
### Description

fixes #938

### CODE REVIEW

File: src/Popover/Popover.js [hunk 1]
```diff
@@ -165,7 +166,7 @@ class Popover extends Component {
                     popperProps={{ ...popperProps, id }}
                     referenceClassName='fd-popover__control'
                     referenceComponent={referenceComponent}
-                    show={this.state.isExpanded && !disabled}
+                    show={typeof this.props.show === 'boolean' ? this.props.show && !disabled : this.state.isExpanded && !disabled}
```
Comment (skvale) [inline src/Popover/Popover.js]:
```js
show={!disabled && (typeof show === 'boolean' ? show : this.state.isExpanded)}
```
To simplify it a little bit, we could take out the repeated `!disabled` as well as use `show` instead of `this.props.show` since it is already deconstructed.

Comment (benoron) [reply src/Popover/Popover.js]: on it

File: src/SearchInput/SearchInput.js [hunk 2]
```diff
@@ -32,6 +32,11 @@ class SearchInput extends Component {
     };
 
     handleListItemClick = (event, item) => {
+        this.setState({
+            value: item.text,
+            isExpanded: false,
+            searchExpanded: false
+        });
         item.callback ? item.callback() : null;
```
Comment (skvale) [inline src/SearchInput/SearchInput.js:40]: I see let calling the onChange callback after setState, we could follow the same pattern.

Also, if you are setting the value in state, it looks like you need to recompute the filteredResult, like this:

```js
        this.setState((prevState) => ({
            value: item.text,
            isExpanded: false,
            searchExpanded: false,
            filteredResult: this.filterList(prevState.searchList, item.text)
        }), () => {
            if (item.callback) {
                item.callback();
            }
        });     
```

Otherwise it can show every item in the list prefixed with the selected text

Screen Shot 2020-04-02 at 10 42 56 AM

instead of

Screen Shot 2020-04-02 at 10 44 12 AM

Comment (BenOron) [reply src/SearchInput/SearchInput.js]: Hi @skvale  and thanks for the review I pushed a new fix.
