### PR TITLE
fix: Add aria attributes to popover control

### LINKED ISSUE #791: Bug: Popover control should have aria attributes for accessibility
### Description
The popover control is not being announced as such by screen readers.
To fix this, the popover control (the trigger) should have following aria attributes:
* [aria-controls](https://www.w3.org/TR/wai-aria-1.1/#aria-controls)
* [aria-expanded](https://www.w3.org/TR/wai-aria-1.1/#aria-expanded)
* [aria-haspopup](https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup)

VoiceOver on Chrome just announces 'button' without indication if it has an associated popover or not and if that popover is open or close:
ACC-1424_no_aria

### Versions
**fundamental-react:** Current
**fundamental-styles:** N/A

### PR DESCRIPTION
**Pull request by prsdthkr**
### Description
Add following aria attributes to popover control/target.
* [aria-controls](https://www.w3.org/TR/wai-aria-1.1/#aria-controls)
* [aria-expanded](https://www.w3.org/TR/wai-aria-1.1/#aria-expanded)
* [aria-haspopup](https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup)

This allows screen readers and other assistive technologies to understand the popover interactions semantically.

fixes #791

### CODE REVIEW

File: src/Popover/Popover.js [hunk 1]
```diff
@@ -79,6 +85,12 @@ class Popover extends Component {
             onClickFunctions = chain(this.triggerBody, control.props.onClick);
         }
 
+        let newPopperProps = !!popperProps ? popperProps : {};
+        // eslint-disable-next-line no-undefined
+        if (newPopperProps.id === undefined || newPopperProps.id === null) {
+            Object.assign(newPopperProps, { id: this.ariaControls });
+        }
```
Comment (markpalfreeman) [inline src/Popover/Popover.js]: I wonder if this could be simplified and avoid the safe checking by:
1) Setting `defaultProps` for `popperProps = {}`
2) Just assigning an `id` inline?
```js
const id = popperProps.id || this.ariaControls;
...
popperProps={{ ...popperProps, id }}
```

File: src/Popover/Popover.js [hunk 2]
```diff
@@ -88,7 +100,9 @@ class Popover extends Component {
                 ...controlProps,
                 tabIndex: 0,
                 role: 'button',
-                'aria-haspopup': true,
+                'aria-controls': newPopperProps.id,
+                'aria-expanded': this.state.isExpanded,
+                'aria-haspopup': !!type ? type : true,
```
Comment (markpalfreeman) [inline src/Popover/Popover.js]: Is this right? The positive/first ternary return type seems like it could end up being a string.
I imagine the intention is a boolean, but when should this be `false`? (there should probably be a test for this)

File: src/Popover/Popover.js [hunk 3]
```diff
@@ -14,6 +15,10 @@ class Popover extends Component {
         this.state = {
             isExpanded: false
         };
+
+        //A generated shortId as fallback, incase props.popperProps.id is unset.
+        //This ID binds the popover and it's control by 'aria-controls'.
+        this.ariaControls = shortId.generate();
```
Comment (meganaconley) [inline src/Popover/Popover.js]: `ariaControls` is a bit confusing - maybe `controlId` would be better?

Comment (prsdthkr) [reply src/Popover/Popover.js]: Since it is not the control's ID how about `popoverId` instead? or `popoverContainerId`?

Comment (markpalfreeman) [reply src/Popover/Popover.js]: Yeah, I think `popoverId` makes sense. It's a bit difficult to distinguish between that and `popperProps.id`, but I think it's clear enough that one comes from props and the other is defined here as a fallback.
