### PR TITLE
chore: cleanup warnings on docs site, small bug fixes and build out forms documentation

### LINKED ISSUE #974: DatePicker: Unknown event handler property `onDatePickerClose`
### Description
While using component DatePicker, there will be an error message in the console said 'Unknown event handler property `onDatePickerClose`' no matter in my application or in the storybook website.
https://deploy-preview939---fundamental-react.netlify.app/datepicker
Screen Shot 2020-04-24 at 4 26 04 PM

I'd like to know how to fix it. Thanks.

### Versions
**fundamental-react:*0.9.0*

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### LINKED ISSUE #993: Calendar: props are not properly documented
### Description

Many props are no properly documented in Calendar - only in Datepicker. 
### Versions
**fundamental-react:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

### PR DESCRIPTION
**Pull request by jbadan**
### Description
This pr does small bug fixes that were causing warnings on the docs site. 

fixes #993 
fixes #974

### CODE REVIEW

File: src/Calendar/Calendar.js [hunk 1]
```diff
@@ -705,14 +715,10 @@ Calendar.basePropTypes = {
         /** aria-label for previous button when years are displayed */
         show12PreviousYears: PropTypes.string
     }),
-    /** Object with special dates and special date types in shape of `{\'YYYYMMDD\': type}`. Type must be a number between 1-20 */
-    specialDays: PropTypes.object
-};
-
-Calendar.propTypes = {
-    ...Calendar.basePropTypes,
```
Comment (skvale) [inline src/Calendar/Calendar.js:713]: Seems like we could do the same thing for `Time.basePropTypes`?

Comment (jbadan) [reply src/Calendar/Calendar.js:713]: Ooo good call! Missed that in the first iteration
